### ISSUE TITLE
HowTo Install and Run on RPi3 ?

### ISSUE THREAD

**Issue by wassfila** [opensmartmesh/osmesh-dashboard#1]
Content is nice, but it looks like a wall to me, or any user not familiar with the framework.
A minimal guidance on how to install and use should be provided.
The easier the steps to have it running on the first time, the more users would adopt it.
It would get even nicer if the HowTo targets the final platform : the Raspberry Pi 3.

**Comment by redotics** [comment]
Now you can read the RTFM. A commit from yesterday was not pushed. Check out the README
